// Static native probe contract: no HWND, device, Qt or WebEngine is created.
#include "../src/native/cleanroom_composition/cleanroom_composition.cpp"
#include <cassert>
#include <climits>
int main() {
    Host ordinaryHost;
    assert(!ordinaryHost.probeSnapshotEnabled && !ordinaryHost.lastSubmittedTexture);
    assert(!ordinaryHost.snapshotRevision && !ordinaryHost.snapshotResourceIdentity);
    Observation observed;
    observed.submittedPresentId=7; observed.lastPresentReturnSeconds=12.5;
    observed.lastFrameMotion=1.; observed.lastFrameContent=1.;
    ProbeIdentity identity;
    identity.snapshotEnabled=1; identity.hostGeneration=9; identity.snapshotRevision=2;
    identity.snapshotResourceIdentity=11; identity.phase=3; identity.submittedPresentId=7;
    identity.presentReturnSeconds=12.5; identity.motion=1.; identity.content=1.;
    assert(probeIdentityMatches(identity,3,observed));
    assert(!probeIdentityMatches(identity,1,observed));
    auto invalidIdentity=identity;
    invalidIdentity.snapshotEnabled=0; assert(!probeIdentityMatches(invalidIdentity,3,observed));
    invalidIdentity=identity; invalidIdentity.hostGeneration=0;
    assert(!probeIdentityMatches(invalidIdentity,3,observed));
    invalidIdentity=identity; invalidIdentity.snapshotRevision=0;
    assert(!probeIdentityMatches(invalidIdentity,3,observed));
    invalidIdentity=identity; invalidIdentity.snapshotResourceIdentity=0;
    assert(!probeIdentityMatches(invalidIdentity,3,observed));
    invalidIdentity=identity; invalidIdentity.subresource=1;
    assert(!probeIdentityMatches(invalidIdentity,3,observed));
    invalidIdentity=identity; invalidIdentity.orientation=0;
    assert(!probeIdentityMatches(invalidIdentity,3,observed));
    invalidIdentity=identity; invalidIdentity.submittedPresentId=6;
    assert(!probeIdentityMatches(invalidIdentity,3,observed));
    invalidIdentity=identity; invalidIdentity.presentReturnSeconds=12.4;
    assert(!probeIdentityMatches(invalidIdentity,3,observed));
    invalidIdentity=identity; invalidIdentity.motion=.99;
    assert(!probeIdentityMatches(invalidIdentity,3,observed));
    invalidIdentity=identity; invalidIdentity.content=.99;
    assert(!probeIdentityMatches(invalidIdentity,3,observed));
    assert(cspm_comp_enable_probe_snapshot(nullptr)==0);
    assert(cspm_comp_probe_identity(nullptr,&identity,sizeof(identity))==0);
    assert(cspm_comp_probe_identity(&ordinaryHost,nullptr,sizeof(identity))==0);
    assert(cspm_comp_probe_identity(&ordinaryHost,&identity,sizeof(identity)-1)==0);
    identity.version=2; assert(cspm_comp_probe_identity(&ordinaryHost,&identity,sizeof(identity))==0);
    identity.version=1; identity.byteSize=199;
    assert(cspm_comp_probe_identity(&ordinaryHost,&identity,sizeof(identity))==0);
    identity.byteSize=200;
    assert(cspm_comp_probe_identity(&ordinaryHost,&identity,sizeof(identity))==1);
    assert(identity.hostGeneration==0 && identity.snapshotRevision==0 && !identity.snapshotEnabled);
    Frame frame;
    frame.desc.Width=100; frame.desc.Height=80; frame.desc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;
    frame.desc.MipLevels=frame.desc.ArraySize=frame.desc.SampleDesc.Count=1;
    FrameIdentity frameIdentity;
    assert(cspm_gpu_frame_identity(nullptr,&frameIdentity,sizeof(frameIdentity))==0);
    assert(cspm_gpu_frame_identity(&frame,nullptr,sizeof(frameIdentity))==0);
    assert(cspm_gpu_frame_identity(&frame,&frameIdentity,sizeof(frameIdentity)-1)==0);
    frameIdentity.version=2; assert(cspm_gpu_frame_identity(&frame,&frameIdentity,sizeof(frameIdentity))==0);
    frameIdentity.version=1; frameIdentity.byteSize=47;
    assert(cspm_gpu_frame_identity(&frame,&frameIdentity,sizeof(frameIdentity))==0);
    frameIdentity.byteSize=48;
    assert(cspm_gpu_frame_identity(&frame,&frameIdentity,sizeof(frameIdentity))==1);
    assert(frameIdentity.revision==frame.revision && frameIdentity.revision);
    assert(frameIdentity.width==100 && frameIdentity.height==80 && frameIdentity.format==DXGI_FORMAT_R8G8B8A8_UNORM);
    assert(frameIdentity.mipLevels==1 && frameIdentity.arraySize==1 && frameIdentity.sampleCount==1);
    assert(frameIdentity.subresource==0 && frameIdentity.orientation==1);
    Frame retainedFrame=frame;
    assert(retainedFrame.revision==frame.revision);
    Host failedHost;
    failedHost.flags.store(1|2);
    const char* firstFailure="Native DXGI presentation slot missed bounded 100 ms readiness";
    failedHost.fail(firstFailure);
    assert(failedHost.flags.load()==(1|2|16));
    // Exercise a rejected follow-up without creating any window or GPU device.
    assert(cspm_comp_transfer_source_visibility(&failedHost,1)==0);
    assert(failedHost.flags.load()==(1|2|16));
    char retainedFailure[256]{};
    assert(cspm_comp_error(&failedHost,retainedFailure,sizeof(retainedFailure))==strlen(firstFailure));
    assert(strcmp(retainedFailure,firstFailure)==0);
    assert(sourceVisibilityBand(true)==HWND_TOPMOST);
    assert(sourceVisibilityBand(false)==HWND_NOTOPMOST);
    assert(sourceVisibilityBandMatches(WS_EX_TOPMOST|WS_EX_NOACTIVATE|WS_EX_TOOLWINDOW,true));
    assert(sourceVisibilityBandMatches(WS_EX_NOACTIVATE|WS_EX_TOOLWINDOW,false));
    assert(!sourceVisibilityBandMatches(WS_EX_TOPMOST,false));
    assert(!sourceVisibilityBandMatches(0,true));
    const int points[]{0,0,99,79};
    assert(probeCoordinatesValid(points,2,100,80,4,6,104,86));
    assert(!probeCoordinatesValid(nullptr,2,100,80,4,6,104,86));
    assert(!probeCoordinatesValid(points,0,100,80,4,6,104,86));
    assert(!probeCoordinatesValid(points,65,100,80,4,6,104,86));
    assert(!probeCoordinatesValid(points,2,99,80,4,6,104,86));
    assert(!probeCoordinatesValid(points,2,100,79,4,6,104,86));
    assert(!probeCoordinatesValid(points,2,100,80,4,6,103,86));
    assert(!probeCoordinatesValid(points,2,100,80,4,6,104,85));
    assert(!probeCoordinatesValid(points,2,100,80,-1,6,104,86));
    const int negative[]{-1,0};
    assert(!probeCoordinatesValid(negative,1,100,80,0,0,100,80));
    const int huge[]{INT_MAX,INT_MAX};
    assert(!probeCoordinatesValid(huge,1,UINT_MAX,UINT_MAX,INT_MAX,INT_MAX,100,100));
    assert(probeEndpointStateValid(1|2|4|8,true,true,true,1.,1.));
    assert(probeEndpointStateValid(1|2|4|8|32,true,true,true,1.,1.));
    for(unsigned required : {1u,2u,4u,8u})
        assert(!probeEndpointStateValid((1|2|4|8)&~required,true,true,true,1.,1.));
    assert(!probeEndpointStateValid(1|2|4|8|16,true,true,true,1.,1.));
    assert(!probeEndpointStateValid(1|2|4|8,false,true,true,1.,1.));
    assert(!probeEndpointStateValid(1|2|4|8,true,false,true,1.,1.));
    assert(!probeEndpointStateValid(1|2|4|8,true,true,false,1.,1.));
    assert(!probeEndpointStateValid(1|2|4|8,true,true,true,.99,1.));
    assert(!probeEndpointStateValid(1|2|4|8,true,true,true,1.,.99));
    unsigned char source[256]{},submitted[256]{};
    assert(cspm_comp_probe_pixels(nullptr,points,2,source,submitted)==0);
    assert(cspm_comp_probe_pixels(nullptr,points,2,nullptr,submitted)==0);
    assert(cspm_comp_probe_pixels(nullptr,points,2,source,nullptr)==0);
    assert(cspm_comp_probe_endpoint_pixels(nullptr,points,2,source,submitted)==0);
    assert(cspm_comp_probe_endpoint_pixels(nullptr,points,2,nullptr,submitted)==0);
    assert(cspm_comp_probe_endpoint_pixels(nullptr,points,2,source,nullptr)==0);
    assert(cspm_comp_probe_frame_pixels(nullptr,nullptr,points,2,source)==0);
    assert(cspm_comp_probe_frame_pixels(nullptr,nullptr,points,2,nullptr)==0);
    assert(cspm_comp_observation(nullptr,nullptr,0)==0);
    assert(cspm_comp_present_trace(nullptr,nullptr,0)==0);
    assert(cspm_comp_defer_source_visibility(nullptr)==0);
    assert(cspm_comp_transfer_source_visibility(nullptr,0)==0);
    assert(cspm_comp_raise_source_visibility(nullptr)==0);
    return 0;
}
